### ISSUE TITLE
Most of the formatted parts of a Record are ignored

### ISSUE THREAD

**Issue by BenceSzalai** [bradmkjr/monolog-wordpress#11]
In WordPressHandler::write there's a line that replaces the items under `$record['extra']` with their formatted counterparts (if available):
`$recordExtra = (isset($record['formatted']['extra'])) ? $record['formatted']['extra'] : $record['extra'];`
However it ignores the rest of the formatted parts, most specifically `$record['context']`.
This seems to be an issue. For example if used with Monolog, the second parameter of the logging calls are assigned to the `'context'` not `'extra'`. And as [PSR-3 suggests to pass exceptions](https://www.php-fig.org/psr/psr-3/#13-context) under the `'exception'` key inside `'context'`, it'd be particularly important to use the formatted `'context'`, not the raw one, as passing the unformatted Exception object (or any other objects) to `$this->wpdb->insert` causes issues.
Is there any reason not to prefer the formatted version of all elements inside `$record`?

**Comment by bradmkjr** [comment]
I've invited you to collab on this repo, if you would like to accept your pull request and or do a version bump that is more then acceptable. 

Thanks,
Brad

**Comment by BenceSzalai** [comment]
Cool, I'll do that, but I was just wondering if I did not understand correctly how the formatters should behave or if there was some specific use-case or reason why it was implemented like that. If not, I'll modify it to use the formatted data whenever available and submit.

**Comment by bradmkjr** [comment]
I haven't personally used this project since I initially wrote it, so I haven't kept up on changes with php, wp or monolog. I appreciate everyones contributions and feedback to make this tool work well for everyone.

Thanks,
Brad

**Comment by BenceSzalai** [comment]
I've built a fix and will test it for a while. If all is good, I'll push it!

**Comment by BenceSzalai** [comment]
> I've invited you to collab on this repo, if you would like to accept your pull request and or do a version bump that is more then acceptable.

Could you set up packagist.org to automatically pull in new version tags from the repo please? r add me a collaborator there as well maybe, whichever you like more. Thanks!

**Comment by bradmkjr** [comment]
It is done, enjoy.
